### ISSUE TITLE
ModellingMonetaryAmountsTest.testImplementComparable does not cover the specification

### ISSUE THREAD

**Issue by oboehm** [JavaMoney/jsr354-tck#18]
For Comparable only two notices appears in section 4.2.2.:

- must be comparable
- Comparison methods for comparing two arbitrary amounts of the same currency, hereby comparing
based on the (effective) numeric value (e.g. ignoring trailing zeroes).

When I run the TCK I get the following error report:

```
[FAILED]  4.2.2 For each amount class, test is Comparable.(ModellingMonetaryAmountsTest#testImplementComparable):
java.lang.AssertionError: Section 4.2.2: Comparable failed for: de.jfachwert.bank.Geldbetrag
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.javamoney.tck.tests.ModellingMonetaryAmountsTest.testImplementComparable(ModellingMonetaryAmountsTest.java:2522)
        ...
```
The input values for failed tests are:

- amount = "0 XXX"
- amount3 = "1 CHF"

The failing assert is `assertTrue(amount.compareTo(amount3) > 0)`, or in other words

> "0 XXX" > "1 CHF" should be true.

This is not covered by the specification (see above - or did I miss something?) and also from the semantic view I would expect it the other way around.

**Comment by marschall** [comment]
I believe the section of the spec you're referring to refers to the `# isGreaterThan` `#isGreaterThanOrEqualTo`, `#isLessThan`, `#isLessThanOrEqualTo` and `#isEqualTo` methods. I understand these methods are supposed to operate on the same currency and throw `MonetaryException` otherwise.
It is my understanding `#equals` and `#compareTo` are supposed to work on different currencies and are not supposed to throw `MonetaryException`.

**Comment by keilw** [comment]
@atsticks Could you have a look and share your thoughts? If any update to the TCK was required, it would be good doing it with the MR1.

**Comment by keilw** [comment]
Seems fixed please reopen or create again, if you still face the problem with 1.1
